from sqlalchemy import delete, select, update
from sqlalchemy.orm import Session

from ..config import get_logger
from ..model import Entity
from ..schema import EntityBase, EntityFilter, EntityFull
from ._crud_base import CrudBase
from ._error_messages import ERROR_MESSAGES

log = get_logger()


"""
CrudEntity is an abstract class that provides a base for creating entities with CRUD (Create, Read,
Update, Delete) operations. It inherits from CrudBase and extends the functionality by providing
methods to handle entities in a database context.
"""


class CrudEntity(CrudBase):
    def change_entity(self, entity: EntityFull):
        """
        Change a Entity object in the database.

        Args:
            entity (EntityBase): The updated data for the entity.

        Returns:
            None

        Raises:
            AttributeError on invalid id.
        """
        with Session(bind=self._engine) as session:
            stmt = update(Entity).where(Entity.id == entity.id).values(name=entity.name)
            result = session.execute(stmt)
            if (
                not result.rowcount  # pyright: ignore[reportUnknownMemberType,reportAttributeAccessIssue]
            ):
                raise AttributeError(
                    ERROR_MESSAGES.NO_SUCH_ID % (Entity.__name__, entity.id)
                )
            session.commit()

    def delete_entity(self, id: int) -> None:
        """
        Deletes an Entity by its unique ID from the database.

        Args:
            id (int): The ID of the Entity to delete.

        Returns:
            None

        Raises:
            AttributeError: If the specified Entity does not exist in the database.
        """
        with Session(bind=self._engine) as session:
            stmt = delete(Entity).where(Entity.id.is_(id))
            result = session.execute(stmt)
            log.error(f"Result Type is: {type(result)}")
            if (
                not result.rowcount  # pyright: ignore[reportUnknownMemberType,reportAttributeAccessIssue]
            ):
                raise AttributeError(ERROR_MESSAGES.NO_SUCH_ID % (Entity.__name__, id))
            session.commit()

    def get_entities(self, filter: EntityFilter | None = None) -> list[EntityFull]:
        """
        Fetches a list of EntityFull objects from the database based on provided filters.
        If no filters are provided, fetches all entities.

        Parameters:
            - filter (EntityFilter | None): An optional filter object to narrow down the search results.
                                           If provided, only entities that match the filter criteria will
                                           be returned. If not provided, all entities will be returned.

        Returns:
            A list of EntityFull objects.
        """
        with Session(bind=self._engine) as session:
            log.debug(
                f"get_entities called with filter: {filter} engine is {self._engine.__hash__}"
            )
            full_entities: list[EntityFull] = []
            stmt = select(Entity)
            if filter and filter.name:
                stmt = stmt.filter(Entity.name.like(filter.name))
            if filter and filter.id:
                stmt = stmt.filter(Entity.id.is_(filter.id))
            for orm_entity in session.execute(stmt).scalars().all():
                full_entities.append(EntityFull(id=orm_entity.id, name=orm_entity.name))
            return full_entities

    def create_entity(self, new_entity: EntityBase) -> EntityFull:
        """
        Creates a new EntityFull object in the database and returns it.

        Args:
            new_entity (EntityBase): The initial data for the new entity.

        Returns:
            EntityFull: The newly created EntityFull object with its id generated by the database.
        """
        with Session(bind=self._engine) as session:
            entity = self._create_entity(session, new_entity)
            session.commit()
            entity_full = EntityFull(id=entity.id, name=entity.name)
            return entity_full

    def _create_entity(self, session: Session, new_entity: EntityBase) -> Entity:
        entity = Entity(name=new_entity.name)
        session.add(entity)
        return entity

    def _get_entity(self, session: Session, entity_full: EntityFull) -> Entity | None:
        stmt = select(Entity).where(Entity.id == entity_full.id)
        return session.execute(stmt).scalars().first()
